#include <iostream>
#include <vector>
#include <string>
#include <fstream>
#include <thread>
using namespace std;


void  drawMenu(){
    //🟥🟧🟨🟩🟦🟪🟫⬜️⬛️
    for (int i = 0; i < 4; i++) {
        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                      \u25A0               " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        chrono::milliseconds search1(70);
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                       \u25A0              " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                        \u25A0             " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                         \u25A0            " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                          \u25A0           " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                           \u25A0          " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                            \u25A0         " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                             \u25A0        " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                             \u25A0        " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                              \u25A0       " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                               \u25A0      " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                                \u25A0     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                                 \u25A0    " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                                  \u25A0   " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                                   \u25A0  " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                                    \u25A0 " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                                     \u25A0" << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;

        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                                     \u25A0" << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                                    \u25A0 " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                                   \u25A0  " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                                  \u25A0   " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                                 \u25A0    " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                                \u25A0     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                               \u25A0      " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                             \u25A0        " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                            \u25A0        " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                           \u25A0         " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                          \u25A0          " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                         \u25A0            " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                        \u25A0             " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;

        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                       \u25A0              " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;

        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                      \u25A0               " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        this_thread::sleep_for(search1);
        cout << "\x1B[2J\x1B[H";
    }
    for (int i = 0; i < 1; i++) {

        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                      \u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0              " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                      \u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0              " << endl;
        chrono::milliseconds search2(1000);
        this_thread::sleep_for(search2);
        cout << "\x1B[2J\x1B[H";

        cout << "\x1B[2J\x1B[H";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                      \u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0              " << endl;
        cout << "                     |=============|" << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                     " << endl;
        cout << "                      \u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0              " << endl;
        this_thread::sleep_for(search2);
        cout << "\x1B[2J\x1B[H";

        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                      \u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0              " << endl;
        cout << "                     |=============|" << endl;
        cout << "                    " << endl;
        cout << "                    " << endl;
        cout << "                     |=============|" << endl;
        cout << "                      \u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0              " << endl;
        this_thread::sleep_for(search2);
        cout << "\x1B[2J\x1B[H";

        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "\n";
        cout << "                      \u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0              " << endl;
        cout << "                     |=============|" << endl;
        cout << "                     |   запуск    |" << endl;
        cout << "                     |   системы   |" << endl;
        cout << "                     |=============|" << endl;
        cout << "                      \u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0              " << endl;
        this_thread::sleep_for(search2);
        cout << "\x1B[2J\x1B[H";
        }
        for (int i = 0; i < 3; i++) {
            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "      " << endl;
            cout << "                     |=============|" << endl;
            cout << "                     |   запуск    |" << endl;
            cout << "                     |   системы   |" << endl;
            cout << "                     |=============|" << endl;
            cout << "      " << endl;
            chrono::milliseconds serch(100);
            this_thread::sleep_for(serch);
            cout << "\x1B[2J\x1B[H";

            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "                      \u25A0\u25A0  " << endl;
            cout << "                     |=============|" << endl;
            cout << "                     |   запуск    |" << endl;
            cout << "                     |   системы   |" << endl;
            cout << "                     |=============|" << endl;
            cout << "                      \u25A0\u25A0  " << endl;
            this_thread::sleep_for(serch);
            cout << "\x1B[2J\x1B[H";

            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "                      \u25A0\u25A0\u25A0\u25A0  " << endl;
            cout << "                     |=============|" << endl;
            cout << "                     |   запуск    |" << endl;
            cout << "                     |   системы   |" << endl;
            cout << "                     |=============|" << endl;
            cout << "                      \u25A0\u25A0\u25A0\u25A0  " << endl;
            this_thread::sleep_for(serch);
            cout << "\x1B[2J\x1B[H";

            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "                      \u25A0\u25A0\u25A0\u25A0\u25A0\u25A0  " << endl;
            cout << "                     |=============|" << endl;
            cout << "                     |   запуск    |" << endl;
            cout << "                     |   системы   |" << endl;
            cout << "                     |=============|" << endl;
            cout << "                      \u25A0\u25A0\u25A0\u25A0\u25A0\u25A0  " << endl;
            this_thread::sleep_for(serch);
            cout << "\x1B[2J\x1B[H";

            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "                      \u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0  " << endl;
            cout << "                     |=============|" << endl;
            cout << "                     |   запуск    |" << endl;
            cout << "                     |   системы   |" << endl;
            cout << "                     |=============|" << endl;
            cout << "                      \u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0  " << endl;
            this_thread::sleep_for(serch);
            cout << "\x1B[2J\x1B[H";

            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "                      \u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0  " << endl;
            cout << "                     |=============|" << endl;
            cout << "                     |   запуск    |" << endl;
            cout << "                     |   системы   |" << endl;
            cout << "                     |=============|" << endl;
            cout << "                      \u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0  " << endl;
            this_thread::sleep_for(serch);
            cout << "\x1B[2J\x1B[H";

            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "\n";
            cout << "                      \u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0  " << endl;
            cout << "                     |=============|" << endl;
            cout << "                     |   запуск    |" << endl;
            cout << "                     |   системы   |" << endl;
            cout << "                     |=============|" << endl;
            cout << "                      \u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0\u25A0  " << endl;
            this_thread::sleep_for(serch);
            cout << "\x1B[2J\x1B[H";
 }
}
